name: Feature Request
description: Suggest an idea for devctl
labels: ["enhancement"]
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of what feature or framework support you would like to see.
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Why is this feature needed and how would it benefit devctl users?
    validations:
      required: true
